#!/bin/bash

# Quick Test Reference Card
# ========================

echo "╔═══════════════════════════════════════════════════════════╗"
echo "║         Mshkltk Automated Testing - Quick Reference        ║"
echo "╚═══════════════════════════════════════════════════════════╝"
echo ""
echo "📊 TEST COVERAGE: 46 Automated Tests"
echo "   ├─ 16 Citizen App Tests"
echo "   ├─ 15 Super Admin Tests"  
echo "   └─ 15 Portal Tests"
echo ""
echo "🚀 QUICK START:"
echo "   1. Start app:      npm run dev"
echo "   2. Run tests:      ./run-tests.sh"
echo "   3. View report:    npm run test:report"
echo ""
echo "📝 COMMANDS:"
echo "   npm test              Run all tests (headless)"
echo "   npm run test:headed   Run with visible browser"
echo "   npm run test:ui       Interactive debugging mode"
echo "   npm run test:citizen  Test citizen features only"
echo "   npm run test:admin    Test admin features only"
echo "   npm run test:portal   Test portal features only"
echo "   npm run test:report   View last test results"
echo ""
echo "📁 FILES:"
echo "   tests/e2e/01-citizen-app.spec.ts    Citizen tests"
echo "   tests/e2e/02-superadmin.spec.ts     Admin tests"
echo "   tests/e2e/03-portal.spec.ts         Portal tests"
echo "   tests/e2e/helpers.ts                Test utilities"
echo "   playwright-report/index.html        Test results"
echo ""
echo "✅ WHAT'S TESTED:"
echo "   • User registration & login"
echo "   • Report submission & viewing"
echo "   • Comments & confirmations"
echo "   • Map functionality"
echo "   • Admin dashboard & management"
echo "   • Portal report resolution"
echo "   • All CRUD operations"
echo "   • Auto-redirect features"
echo "   • Gamification system"
echo ""
echo "🐛 DEBUGGING:"
echo "   Failed tests generate:"
echo "   • Screenshots (moment of failure)"
echo "   • Videos (full test replay)"
echo "   • Console logs (step-by-step)"
echo ""
echo "💡 TIP: Run 'npm run test:ui' for interactive debugging"
echo ""
echo "═══════════════════════════════════════════════════════════"
